In [46]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.ensemble import RandomForestClassifier
from sklearn import tree

In [10]:
ds = pd.read_csv('./titanic.csv')
ds2 = pd.read_csv('./test.csv')

In [16]:
mean_Age = ds2['Age'].mean()
ds2['Age'] = ds2['Age'].fillna(int(mean_Age))
ds2['Fare'] = ds['Fare'].fillna(ds2['Fare'].mean())

sex_mapping = {
    'male': 0,
    'female': 1
}

sex = ds2['Sex'].values
quant_sex2 = np.zeros(sex.shape)

for ix in range(quant_sex2.shape[0]):
    quant_sex2[ix] = sex_mapping[sex[ix]]

In [17]:
mean_Age = ds['Age'].mean()
ds['Age'] = ds['Age'].fillna(int(mean_Age))

sex_mapping = {
    'male': 0,
    'female': 1
}

sex = ds['Sex'].values
quant_sex = np.zeros(sex.shape)

for ix in range(quant_sex.shape[0]):
    quant_sex[ix] = sex_mapping[sex[ix]]

In [21]:
data = np.asarray([ds['Age'], ds['Pclass'], ds['SibSp'], ds['Parch'], ds['Fare'], quant_sex]).astype("float").T

test_data = np.asarray([ds2['Age'], ds2['Pclass'], ds2['SibSp'], ds2['Parch'], ds2['Fare'], quant_sex2]).astype("float").T

In [22]:
ds2.describe()

       PassengerId      Pclass         Age       SibSp       Parch        Fare
count   418.000000  418.000000  418.000000  418.000000  418.000000  418.000000
mean   1100.500000    2.265550   30.216507    0.447368    0.392344   32.521560
std     120.810458    0.841838   12.635016    0.896760    0.981429   49.328086
min     892.000000    1.000000    0.170000    0.000000    0.000000    0.000000
25%     996.250000    1.000000   23.000000    0.000000    0.000000    7.925000
50%    1100.500000    3.000000   30.000000    0.000000    0.000000   14.454200
75%    1204.750000    3.000000   35.750000    1.000000    0.000000   30.923950
max    1309.000000    3.000000   76.000000    8.000000    9.000000  512.329200

In [58]:
X_train = data[:, :]
y_train = data[:, -1]

X_test = test_data

dt = tree.DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)

rf = RandomForestClassifier(n_estimators=25)
rf.fit(X_train, y_train)
clf_probs = rf.predict_proba(X_test)

y_pred_rf = np.zeros(y_pred.shape)

for ix in range(clf_probs.shape[0]):
    y_pred_rf[ix] = clf_probs[ix].argmax()

count = 0
for ix in range(len(y_pred)):
    if y_pred[ix] != y_pred_rf[ix]:
        count += 1

print count
#Therefore, exactly the same result with our custom DT, sklearn DT, sklearn RF

0

In [38]:
final_ans = np.zeros((len(y_pred), 2)).astype('int')
final_ans[:,0] = ds2['PassengerId']
final_ans[:,1] = y_pred
print final_ans

[[ 892    0]
 [ 893    1]
 [ 894    0]
 [ 895    0]
 [ 896    1]
 [ 897    0]
 [ 898    1]
 [ 899    0]
 [ 900    1]
 [ 901    0]
 [ 902    0]
 [ 903    0]
 [ 904    1]
 [ 905    0]
 [ 906    1]
 [ 907    1]
 [ 908    0]
 [ 909    0]
 [ 910    1]
 [ 911    1]
 [ 912    0]
 [ 913    0]
 [ 914    1]
 [ 915    0]
 [ 916    1]
 [ 917    0]
 [ 918    1]
 [ 919    0]
 [ 920    0]
 [ 921    0]
 [ 922    0]
 [ 923    0]
 [ 924    1]
 [ 925    1]
 [ 926    0]
 [ 927    0]
 [ 928    1]
 [ 929    1]
 [ 930    0]
 [ 931    0]
 [ 932    0]
 [ 933    0]
 [ 934    0]
 [ 935    1]
 [ 936    1]
 [ 937    0]
 [ 938    0]
 [ 939    0]
 [ 940    1]
 [ 941    1]
 [ 942    0]
 [ 943    0]
 [ 944    1]
 [ 945    1]
 [ 946    0]
 [ 947    0]
 [ 948    0]
 [ 949    0]
 [ 950    0]
 [ 951    1]
 [ 952    0]
 [ 953    0]
 [ 954    0]
 [ 955    1]
 [ 956    0]
 [ 957    1]
 [ 958    1]
 [ 959    0]
 [ 960    0]
 [ 961    1]
 [ 962    1]
 [ 963    0]
 [ 964    1]
 [ 965    0]
 [ 966    1]
 [ 967    0]
 [ 968    0]
 [ 969    1]
 [ 970    0]
 [ 971    1]
 [ 972    0]
 [ 973    0]
 [ 974    0]
 [ 975    0]
 [ 976    0]
 [ 977    0]
 [ 978    1]
 [ 979    1]
 [ 980    1]
 [ 981    0]
 [ 982    1]
 [ 983    0]
 [ 984    1]
 [ 985    0]
 [ 986    0]
 [ 987    0]
 [ 988    1]
 [ 989    0]
 [ 990    1]
 [ 991    0]
 [ 992    1]
 [ 993    0]
 [ 994    0]
 [ 995    0]
 [ 996    1]
 [ 997    0]
 [ 998    0]
 [ 999    0]
 [1000    0]
 [1001    0]
 [1002    0]
 [1003    1]
 [1004    1]
 [1005    1]
 [1006    1]
 [1007    0]
 [1008    0]
 [1009    1]
 [1010    0]
 [1011    1]
 [1012    1]
 [1013    0]
 [1014    1]
 [1015    0]
 [1016    0]
 [1017    1]
 [1018    0]
 [1019    1]
 [1020    0]
 [1021    0]
 [1022    0]
 [1023    0]
 [1024    1]
 [1025    0]
 [1026    0]
 [1027    0]
 [1028    0]
 [1029    0]
 [1030    1]
 [1031    0]
 [1032    1]
 [1033    1]
 [1034    0]
 [1035    0]
 [1036    0]
 [1037    0]
 [1038    0]
 [1039    0]
 [1040    0]
 [1041    0]
 [1042    1]
 [1043    0]
 [1044    0]
 [1045    1]
 [1046    0]
 [1047    0]
 [1048    1]
 [1049    1]
 [1050    0]
 [1051    1]
 [1052    1]
 [1053    0]
 [1054    1]
 [1055    0]
 [1056    0]
 [1057    1]
 [1058    0]
 [1059    0]
 [1060    1]
 [1061    1]
 [1062    0]
 [1063    0]
 [1064    0]
 [1065    0]
 [1066    0]
 [1067    1]
 [1068    1]
 [1069    0]
 [1070    1]
 [1071    1]
 [1072    0]
 [1073    0]
 [1074    1]
 [1075    0]
 [1076    1]
 [1077    0]
 [1078    1]
 [1079    0]
 [1080    1]
 [1081    0]
 [1082    0]
 [1083    0]
 [1084    0]
 [1085    0]
 [1086    0]
 [1087    0]
 [1088    0]
 [1089    1]
 [1090    0]
 [1091    1]
 [1092    1]
 [1093    0]
 [1094    0]
 [1095    1]
 [1096    0]
 [1097    0]
 [1098    1]
 [1099    0]
 [1100    1]
 [1101    0]
 [1102    0]
 [1103    0]
 [1104    0]
 [1105    1]
 [1106    1]
 [1107    0]
 [1108    1]
 [1109    0]
 [1110    1]
 [1111    0]
 [1112    1]
 [1113    0]
 [1114    1]
 [1115    0]
 [1116    1]
 [1117    1]
 [1118    0]
 [1119    1]
 [1120    0]
 [1121    0]
 [1122    0]
 [1123    1]
 [1124    0]
 [1125    0]
 [1126    0]
 [1127    0]
 [1128    0]
 [1129    0]
 [1130    1]
 [1131    1]
 [1132    1]
 [1133    1]
 [1134    0]
 [1135    0]
 [1136    0]
 [1137    0]
 [1138    1]
 [1139    0]
 [1140    1]
 [1141    1]
 [1142    1]
 [1143    0]
 [1144    0]
 [1145    0]
 [1146    0]
 [1147    0]
 [1148    0]
 [1149    0]
 [1150    1]
 [1151    0]
 [1152    0]
 [1153    0]
 [1154    1]
 [1155    1]
 [1156    0]
 [1157    0]
 [1158    0]
 [1159    0]
 [1160    1]
 [1161    0]
 [1162    0]
 [1163    0]
 [1164    1]
 [1165    1]
 [1166    0]
 [1167    1]
 [1168    0]
 [1169    0]
 [1170    0]
 [1171    0]
 [1172    1]
 [1173    0]
 [1174    1]
 [1175    1]
 [1176    1]
 [1177    0]
 [1178    0]
 [1179    0]
 [1180    0]
 [1181    0]
 [1182    0]
 [1183    1]
 [1184    0]
 [1185    0]
 [1186    0]
 [1187    0]
 [1188    1]
 [1189    0]
 [1190    0]
 [1191    0]
 [1192    0]
 [1193    0]
 [1194    0]
 [1195    0]
 [1196    1]
 [1197    1]
 [1198    0]
 [1199    0]
 [1200    0]
 [1201    1]
 [1202    0]
 [1203    0]
 [1204    0]
 [1205    1]
 [1206    1]
 [1207    1]
 [1208    0]
 [1209    0]
 [1210    0]
 [1211    0]
 [1212    0]
 [1213    0]
 [1214    0]
 [1215    0]
 [1216    1]
 [1217    0]
 [1218    1]
 [1219    0]
 [1220    0]
 [1221    0]
 [1222    1]
 [1223    0]
 [1224    0]
 [1225    1]
 [1226    0]
 [1227    0]
 [1228    0]
 [1229    0]
 [1230    0]
 [1231    0]
 [1232    0]
 [1233    0]
 [1234    0]
 [1235    1]
 [1236    0]
 [1237    1]
 [1238    0]
 [1239    1]
 [1240    0]
 [1241    1]
 [1242    1]
 [1243    0]
 [1244    0]
 [1245    0]
 [1246    1]
 [1247    0]
 [1248    1]
 [1249    0]
 [1250    0]
 [1251    1]
 [1252    0]
 [1253    1]
 [1254    1]
 [1255    0]
 [1256    1]
 [1257    1]
 [1258    0]
 [1259    1]
 [1260    1]
 [1261    0]
 [1262    0]
 [1263    1]
 [1264    0]
 [1265    0]
 [1266    1]
 [1267    1]
 [1268    1]
 [1269    0]
 [1270    0]
 [1271    0]
 [1272    0]
 [1273    0]
 [1274    1]
 [1275    1]
 [1276    0]
 [1277    1]
 [1278    0]
 [1279    0]
 [1280    0]
 [1281    0]
 [1282    0]
 [1283    1]
 [1284    0]
 [1285    0]
 [1286    0]
 [1287    1]
 [1288    0]
 [1289    1]
 [1290    0]
 [1291    0]
 [1292    1]
 [1293    0]
 [1294    1]
 [1295    0]
 [1296    0]
 [1297    0]
 [1298    0]
 [1299    0]
 [1300    1]
 [1301    1]
 [1302    1]
 [1303    1]
 [1304    1]
 [1305    0]
 [1306    1]
 [1307    0]
 [1308    0]
 [1309    0]]

In [43]:
final = pd.DataFrame({'PassengerId': final_ans[:, 0], 'Survived': final_ans[:, 1]})
final.to_csv('output-sklearn.csv', header=True, columns = ['PassengerId', 'Survived'], sep = ',', index = False)

In [44]:
ds = pd.read_csv('./output-sklearn.csv')
ds.head(n=418)

     PassengerId  Survived
0            892         0
1            893         1
2            894         0
3            895         0
4            896         1
5            897         0
6            898         1
7            899         0
8            900         1
9            901         0
10           902         0
11           903         0
12           904         1
13           905         0
14           906         1
15           907         1
16           908         0
17           909         0
18           910         1
19           911         1
20           912         0
21           913         0
22           914         1
23           915         0
24           916         1
25           917         0
26           918         1
27           919         0
28           920         0
29           921         0
..           ...       ...
388         1280         0
389         1281         0
390         1282         0
391         1283         1
392         1284         0
393         1285         0
394         1286         0
395         1287         1
396         1288         0
397         1289         1
398         1290         0
399         1291         0
400         1292         1
401         1293         0
402         1294         1
403         1295         0
404         1296         0
405         1297         0
406         1298         0
407         1299         0
408         1300         1
409         1301         1
410         1302         1
411         1303         1
412         1304         1
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         0

[418 rows x 2 columns]